### ISSUE TITLE
change header color

### ISSUE THREAD

**Issue by ifatroz** [doriroz/list-for-travel#1]
i think header color would be nice like the one below;

```css
.add-form button {
  text-transform: uppercase;
  background-color: #53bd9b;
}
```
